name: Unit Test

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 9
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i
      - name: Check Linting
        run: pnpm lint:check
      - name: Check Tests
        run: pnpm test
